name: build and publish RAPIDS manylinux

on:
  workflow_call:
    inputs:
      push:
        required: true
        type: boolean

jobs:
  docker-manylinux:
    name: manylinux ${{ matrix.labels[2] }}
    runs-on: ${{ matrix.labels }}
    strategy:
      matrix:
        include:
          - labels: [self-hosted, linux, amd64, cpu4]
            cpu-arch: x86_64
          - labels: [self-hosted, linux, arm64, cpu4]
            cpu-arch: aarch64
    env:
      DOCKERHUB_USERNAME: ${{ secrets.GPUCIBOT_DOCKERHUB_USER }}
      DOCKERHUB_TOKEN: ${{ secrets.GPUCIBOT_DOCKERHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'true'
      - if: ${{ env.DOCKERHUB_USERNAME != '' && env.DOCKERHUB_TOKEN != '' }}
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}
      - name: Set up Docker Context for Buildx
        id: buildx-context
        run: docker context create builders
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          endpoint: builders
      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: .buildx-cache-manylinux_2_31_${{ matrix.cpu-arch }}/*
          key: buildx-cache-manylinux_2_31-${{ matrix.cpu-arch }}-${{ hashFiles('docker/**') }}
          restore-keys: buildx-cache-manylinux_2_31-${{ matrix.cpu-arch }}-
      - name: Build manylinux_2_31 base container
        run: >
          MANYLINUX_2_31_BASE_OVERRIDE="nvidia/cuda:11.5.1-devel-ubuntu20.04"
          PLATFORM=${{ matrix.cpu-arch }}
          COMMIT_SHA=latest
          POLICY=manylinux_2_31
          ./build.sh
      - name: Re-tag as rapidsai/manylinux_2_31 containers
        run: docker tag quay.io/pypa/manylinux_2_31_${{ matrix.cpu-arch }} rapidsai/manylinux_2_31_${{ matrix.cpu-arch }}
      - name: Push rapidsai/manylinux containers to DockerHub
        if: ${{ inputs.push }}
        run: docker push rapidsai/manylinux_2_31_${{ matrix.labels[2] }}
