name: RAPIDS manylinux release

on:
  push:
    branches:
      - "manylinux*cuda"

jobs:
  build-images:
    uses: ./.github/workflows/build-and-publish.yml
    with:
      push: true
    secrets: inherit
